mkdir DoxygenToolkit
mkdir EnhancedCommentify-2
mkdir SearchComplete
mkdir TrimEnabler
mkdir autoclose
mkdir clang_complete
mkdir ctagloader
mkdir latexSuite-1
mkdir lookupfile-1
mkdir nerdcommenter
mkdir omnicppcomplete-0
mkdir perl-support
mkdir snipMate
mkdir surround
mkdir vimExplorer
